import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Quicksand } from "next/font/google";
import { Toaster } from "sonner";
import BgChanger from "./components/BgChanger/BgChanger";
import NavbarToggle from "./components/Navbar/NavbarToggle";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import QueryClientProvider from "./QueryClientProvider";
import "./theme-config.css";
import ThemeSwitcher from "./ThemeSwitcher";
import { ToastContainer } from "react-toastify";

const quickSand = Quicksand({
  variable: "--font-quick-sand",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ramzan Dastar Khwan",
  description:
    "Generated by Access Solution, Design by M. Qamar Shahzad, Developed by Israr Rashid",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${quickSand.variable} antialiased`}
      >
        <ReduxProvider>
          <ThemeSwitcher>
            <QueryClientProvider>
              <NavbarToggle />
              <main className="py-5 px-2 sm:px-10 lg:px-12.5 xl:px-25">
                {children}
              </main>
            </QueryClientProvider>
            <div className="fixed bg-(--green-9) w-full bottom-0 z-10 pointer-events-none">
              <footer className="text-white bg-color-sea-blue text-center py-1">
                Ramzan Dastar Khwan by FSCPD
              </footer>
            </div>
          </ThemeSwitcher>
        </ReduxProvider>
        <Toaster richColors position="top-right" />
        <BgChanger />
        <ToastContainer />
      </body>
    </html>
  );
}
